### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by melpsain** [melpsain/stat679work#3]
@cecileane I have submitted my homework 3.  The link below is the link to my commit for homework 3. https://github.com/melpsain/stat679work/commit/70d5231a769ceb04bd9774c746c1492cf2adcf22

**Comment by cecileane** [comment]
Hi Melody,

I had issues to run your code, but was able to debug it for the most part. More details below.

## overall presentation

Your directory structure could be improved: your directory `hw2/` has a subdirectory `hw2/hw2-datamerge/` and a readme file, but this readme file really belonged into `hw2/hw2-datamerge/` (which contained all the real stuff) and it would have been better to have different directories for the scripts, and the input/output files.

Your readme file says that the script to use is `datamerger.py`, which is great. A step further would be to explain how to use this script on the command line: give an example to explain what arguments it takes.

You made good use of markdown style.

## running your script

Doing `python datamerge.py -h` gave a helpful error message about how I show go about to run your script. Good use of the argparse module! So I tried `python datamerge.py -t waterTemperature.csv -e energy.csv`.

I saw that a new file had appeared, `solarEnergyTempLog.csv `, but it was empty. It looks like it's because your script opens the file, defines a function `solarenergy_temp` (that should write something to the file), but your function is not called.
I added a call to the function in your script: ``
and re-ran it. But I got an error message:

```shell
$ python datamerge.py -t waterTemperature.csv -e energy.csv
Traceback (most recent call last):
  File "datamerge.py", line 71, in <module>
    solarenergy_temp(args.t, args.e)
  File "datamerge.py", line 69, in solarenergy_temp
    OutFile.write(tempData+'\n')
TypeError: can only concatenate list (not "str") to list
```

After looking deeper into your code, there were 3 issues:
- tempData is a list of lists, not a single string
- it contains the full data for all rows and all columns, so writing its content to the output file should be done once only, not once for each row.
- individual items in tempData were not strings, but floating-point values or strings

Your code worked after I replaced line 67:

```python
            OutFile.write(tempData+'\n')
```

by this block, indented differently (to take it outside the `for i in energy`):

```python
    for row in tempData:
        for item in row:
            OutFile.write(str(item))
        OutFile.write('\n')
```

I made a commit with these changes: https://github.com/melpsain/stat679work/commit/df57897ee873449621b430505b4dbdaf64162aac.

The output was almost perfect, except for a warning message that was written on the first line, and for missing commas to make this file a csv file:

```
$ cat solarEnergyTempLog.csv
107/29/16 10:26:34 AM72.862.956 warning: this energy value was recorded after this time
207/29/16 11:26:34 AM73.92
307/29/16 12:26:34 PM73.98
...
1307/29/16 10:26:34 PM73.27
1407/29/16 11:26:34 PM73.459.468
1507/30/16 12:26:34 AM72.30
...
36108/13/16 10:26:34 AM70.79
36208/13/16 11:26:34 AM73.06
36308/13/16 12:26:34 PM76.39
```

Adding commas would be a matter or tweaking the code that I inserted, to print commas between items. The output file would also need an extra header line at the beginning to give a name to each column.

## about your code

Your code would benefit from being broken down into separate functions. You have only one function, `solarenergy_temp`, which does everything: read the temperature file, read the energy file, and then write the output file.

Nice use of regular expressions to parse the dates!

You also need more comments, for example to explain the key steps of the algorithm near the lines that do the key steps. You have a docstring for your function, but it seems outdated because it talks about `temp` and `energy` arguments, when the arguments are `t` and `e`, and the file names are not hard-coded.

If a comment had said what `tempData` contains, for instance, it would have been easier for me to debug the error at the end, to write `tempData` to the output file.

You coded the algorithm correctly, great job!
